[demo]
vm-demo

[demo:vars]
ansible_host="{{ lookup('env', 'DEMO_SSH_HOST') | default('127.0.0.1', true) }}"
ansible_user="{{ lookup('env', 'DEMO_SSH_USER') | default('deploy', true) }}"
ansible_ssh_private_key_file="{{ lookup('env', 'DEMO_SSH_KEY_PATH') | default('~/.ssh/id_rsa', true) }}"
ansible_python_interpreter=/usr/bin/python3
